.MODEL SMALL
.STACK
.DATA
;VARIABLES PARA LOS MENSAJES
MSGDIVISION DB 'EL RESULTADO DE LA DIVISION ES: $'
MSGRESIDUO DB 'EL RESIDUO ES: $'
MSGPRODUCTO DB 'EL PRODUCTO ES $'
MSGINGRESO DB 'INGRESE UN NUMERO$'
;VARIABLE PARA LOS RESULTRANTES
NUMERO1 DB ? 
NUMERO2 DB ? 
NUMEROBAN DB ?
NUMEROBAN2 DB ?
RESIDUO DB ? , '$'
RESULTADO DB ? ,'$'
RESULTADO2 DB ?
RESULTADO3 DB ?
RESULTADORESTA DB ?
.CODE
PROGRAMA:
;INICIALIZAMOS EL PROGRAMA 
MOV AX,@DATA
MOV DS,AX

;MOSTRAR EL MENSAJE MSGINGRESO PARA INGRESAR LOS NUMEROS
XOR AX,AX
MOV DX, OFFSET MSGINGRESO
MOV AH,09H
INT 21H

;GUARDAR EL DATO INGRESADO EN NUMERO1
XOR AX,AX
MOV AH,01H
INT 21H
MOV NUMERO1,AL
MOV NUMEROBAN2,AL
SUB NUMERO1,30H
SUB NUMEROBAN2,30H


;MOSTRAR EL MENSAJE MSGINGRESO PARA INGRESAR LOS NUMEROS
XOR AX,AX
MOV DX, OFFSET MSGINGRESO
MOV AH,09H
INT 21H

;GUARDAR EL DATO INGRESADO EN NUMERO2
XOR AX,AX
XOR AL,AL
MOV AH,01H
INT 21H
MOV NUMERO2,AL
MOV NUMEROBAN,AL

SUB NUMERO2,30H
SUB NUMEROBAN,30H


;PARA HACER LA MULTIPLICACION
VALIDAR0:
    ;VALIDA SI EL PRIMER NUMERO ES 0
    XOR DL,DL
    MOV DL,NUMERO1
    CMP DL,0H
    MOV RESULTADO2,0
    JZ IMPRIMIRPRO
    ;VALIDAR SI EL SEGUNDO NUMERO ES 0
    XOR DL,DL
    MOV DL,NUMERO2
    CMP DL,0H
    MOV RESULTADO2,0
    JZ IMPRIMIRPRO
    
    
RESTA1:
    
    XOR AL,AL
    SUB NUMEROBAN,1
    MOV AL,NUMERO1
    MOV RESULTADO2,AL 
    JMP VALIDARPRO
    
VALIDARPRO:
    XOR AX,AX
    CMP NUMEROBAN,0H
    JG REALIZARSUMA
    JMP IMPRIMIRPRO 
    

REALIZARSUMA:
    SUB NUMEROBAN,1H
    XOR AL,AL
    MOV AL,NUMERO1
    ADD RESULTADO2,AL
    JMP VALIDARPRO



IMPRIMIRPRO:
;IMPRIME MENSAJE PRODUCTO
    XOR AX,AX
    MOV DX, OFFSET MSGPRODUCTO
    MOV AH,09H
    INT 21H
;IMPRIME EL NUMERO RESULTANTE
    XOR AX,AX
    XOR DL,DL
    MOV DL,RESULTADO2
    ADD DL,30H
    MOV RESULTADO,DL
    MOV DX,OFFSET RESULTADO
    MOV AH,09H
    INT 21H

;HACE LA DIVISION

VALIDADO:
    ;VALIDA SI EL PRIMER NUMERO ES 0
    XOR AX,AX
    XOR AL,AL
    MOV AL,NUMERO1
    CMP AL,0H
    ;MOV RESULTADO3,0
    JZ IMPRIMIRDIV
    
MOV AL, NUMERO1
MOV RESULTADORESTA,AL
;ADD RESULTADO3,01H

VALIDARDIV:
    XOR AX,AX
    MOV AL,NUMERO2
    CMP RESULTADORESTA,AL
    JG RESTA
    JZ RESTA
    XOR AX,AX
    MOV AL,RESULTADORESTA
    MOV RESIDUO,AL
    JMP IMPRIMIRDIV

RESTA:
    ADD RESULTADO3,01H
    XOR AX,AX
    MOV AL, NUMERO2
    SUB RESULTADORESTA,AL
    JMP VALIDARDIV 
    
IMPRIMIRDIV:
;IMPRIME MENSAJE PRODUCTO
    XOR AX,AX
    MOV DX, OFFSET MSGDIVISION
    MOV AH,09H
    INT 21H
;IMPRIME EL NUMERO RESULTANTE
    XOR AX,AX
    XOR DL,DL
    MOV AL,RESULTADO3
    ADD AL,30H
    MOV RESULTADO,AL
    MOV DX,OFFSET RESULTADO
    MOV AH,09H
    INT 21H
    ;IMPRIME EL RESIDUO DE LA DIVISION
    XOR AX,AX
    MOV DX, OFFSET MSGRESIDUO
    MOV AH,09H
    INT 21H
    ADD RESIDUO,30H
    MOV DX,OFFSET RESIDUO
    MOV AH,09H
    INT 21H
    
;TERMINA EL PROGRAMA
TERMINAR:
MOV AH,4CH
INT 21H
END PROGRAMA