.MODEL SMALL
.STACK
.DATA

MSGIGUALES DB 'LOS NUMEROS SON IGUALES$'
MSGMAYOR1 DB 'EL PRIMER NUMERO ES MAYOR$'
MSGMAYOR2 DB 'EL SEGUNDO NUMERO ES MAYOT$'
MSGINGRESO DB 'INGRESE UN NUMERO$'
NUMERO1 DB ?
NUMERO2 DB ?
.CODE
PROGRAMA:

;INICIALIZAMOS EL PROGRAMA
MOV AX,@DATA
MOV DS, AX

;MOSTRAR EL MENSAJE MSGINGRESO PARA EL PRIMER NUMERO
XOR AX,AX
MOV DX, OFFSET MSGINGRESO
MOV AH,09H
INT 21H

;GUARDAR EL PRIMER DATO INGRESADO EN NUMERO1
XOR AX,AX
MOV AH,01H
INT 21H
MOV NUMERO1,AL
SUB NUMERO1,30H

;MOSTRAR EL MENSAJE MSGINGRESO PARA EL SEGUNDO NUMERO
XOR AX,AX
MOV DX, OFFSET MSGINGRESO
MOV AH,09H
INT 21H

;GUARDAR EL PRIMER DATO INGRESADO EN NUMERO2
XOR AX,AX
MOV AH,01H
INT 21H
MOV NUMERO2,AL
SUB NUMERO2,30H

;COMPARA EL NUMERO1 CON EL NUMERO2
XOR AL,AL
MOV AL,NUMERO1
CMP AL,NUMERO2
JZ IMPIGUALES
JG IMPPRIMERO
JMP IMPSEGUNDO

;IMPRIMIR QUE LOS NUMEROS SON IGUALES
IMPIGUALES:
    XOR AX,AX
    MOV DX, OFFSET MSGIGUALES
    MOV AH,09H
    INT 21H
    JMP TERMINAR

IMPPRIMERO:
    XOR AX,AX
    MOV DX, OFFSET MSGMAYOR1
    MOV AH,09H
    INT 21H
    JMP TERMINAR
    
IMPSEGUNDO:
    XOR AX,AX
    MOV DX, OFFSET MSGMAYOR2
    MOV AH,09H
    INT 21H
    JMP TERMINAR

;TERMINA EL PROGRAMA
TERMINAR:
MOV AH,4CH
INT 21H

END PROGRAMA